plugins {
    id 'application'
    id 'com.github.ben-manes.versions' version '0.51.0'
}

group = 'de.codevibe'
version = '040'

ext {
    springVersion = '7.0.9'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'pizza.PizzaApp'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.springframework:spring-context:${springVersion}"
    implementation "org.springframework:spring-test:${springVersion}"
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.github.freva:ascii-table:1.12.1'
}

test {
    useJUnitPlatform()
}