GET http://localhost:8080/products

###

GET http://localhost:8080/products/P-11

###

GET http://localhost:8080/customers

###

POST http://localhost:8080/customers
Content-Type: application/json

{
  "fullName": "Enrico Pallazzo",
  "address": {
    "street": "Wasserstr. 123",
    "postalCode": "40302",
    "city": "Atlantis"
  },
  "phoneNumber": "+49 123 456789"
}

###

GET http://localhost:8080/orders

###

POST http://localhost:8080/orders
Content-Type: application/json

{
  "phoneNumber": "+49 123 456789",
  "itemQuantities": {
    "P-11": 3,
    "P-12": 1
  }
}