#
# application settings
#
app.order.delivery-time-in-minutes=12
app.order.discount-days=MONDAY, TUESDAY
app.order.discount-rate=6.5
app.order.greeting=Welcome dear customer!
app.data-loader=csv
app.data-loader.csv.product-data=classpath:products.csv
